module "lambda" {
  source                    = "../../modules/lambda"
  lambda_timeout            = 900
  lambda_memory_size        = 128
  subnet_ids                = module.vpc.private_subnets[*].id
  security_group_ids        = [module.private_sg.aurora_sg_id]
  cookie_domain             = var.domain_name
  jwt_secret_key            = "38b0ab2ea67a66315f3117518db7943b09ab281e362b9fd4a293704324eb0404"
  aurora_credentials        = module.secrets_manager.aurora_credentials
  aws_region                = var.aws_region
  db_shard_count            = 2
  rds_cluster_instance_url  = module.aurora.rds_cluster_instance_url
  common_dbname             = "tend_attend_common"
  sequence_dbname           = "tend_attend_sequence"
  shard_dbname_prefix       = "tend_attend_shard"
  ml_server_url             = module.cloud_run.ml_server_url
  allow_origins             = ["https://${var.domain_name}"]
  qrcode_lambda_timeout     = 60
  qrcode_lambda_memory_size = 128
}
