module "lambda" {
  source                    = "../../modules/lambda"
  subnet_ids                = module.vpc.private_subnets[*].id
  security_group_ids        = [module.private_sg.aurora_sg_id]
  allow_origins             = ["https://${var.domain_name}"]
  server_lambda_timeout     = 900
  server_lambda_memory_size = 128
  cookie_domain             = var.domain_name
  jwt_secret_key            = module.op.jwt_secret_key
  aurora_credentials        = module.secrets_manager.aurora_credentials
  aws_region                = var.aws_region
  db_shard_count            = module.op.db_shard_count
  rds_cluster_instance_url  = module.aurora.rds_cluster_instance_url
  common_dbname             = module.op.common_dbname
  sequence_dbname           = module.op.sequence_dbname
  shard_dbname_prefix       = module.op.shard_dbname_prefix
  ml_server_url             = module.cloud_run.ml_server_url
  qrcode_ecr_repository_url = module.ecr.qrcode_ecr_repository_url
  qrcode_lambda_timeout     = 60
  qrcode_lambda_memory_size = 128
  domain_name               = var.domain_name
  depends_on                = [module.ecr]
}
