name: ci-test

on:
  push:
    branches:
      - develop
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: tend_attend_common
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        volumes:
          - ${{ github.workspace }}/docker/mysql/conf.d:/etc/mysql/conf.d
          - ${{ github.workspace }}/docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python for ta-api
        uses: actions/setup-python@v5
        with:
          python-version-file: "ta-api/.python-version"
      - name: Set up Python for ta-ml
        uses: actions/setup-python@v5
        with:
          python-version-file: "ta-ml/.python-version"
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python -
          ./scripts/poetry-all.sh install
      - name: Run Lint
        run: |
          ./scripts/poe-all.sh lint
          ./scripts/poe-all.sh format
      - name: Run Tests
        run: DB_SHARD_COUNT=2 ./scripts/poe-all.sh test
